import turtle
turtle.Screen().bgcolor("blue")
s=turtle.Screen()
s.setup(500,500)
turtle.title("welcome to the new turtles website")
bd=turtle.Turtle()
bd.forward(100)
bd.left(90)
bd.forward(100)
bd.left(90)
bd.forward(100)
bd.left(90)
bd.forward(100)
bd.left(90)
turtle.done()